#
# Copyright 2019 GridGain Systems, Inc. and Contributors.
#
# Licensed under the GridGain Community Edition License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.gridgain.com/products/software/community-edition/gridgain-community-edition-license
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2.2'
services:
  backend:
    build:
      context: '../docker/console'
      dockerfile: 'backend/Dockerfile'
    environment:
      - SPRING_PROFILES_ACTIVE=test
    cpu_count: 4

  frontend:
    build:
      context: '../docker/console'
      dockerfile: 'frontend/Dockerfile'
    depends_on:
      - backend

  e2e:
    build: './testcafe'
    environment:
      - APP_URL=http://frontend:8008
      - REPORTER=teamcity
      - QUARANTINE_MODE=true
    depends_on:
      - frontend
    entrypoint: dockerize -wait http://backend:3000/health -timeout 2m -wait-retry-interval 5s node ./index.js
